# Este arquivo define o servi√ßo do DynamoDB Local
version: "3.8"
services:
  dynamo:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000" # Mapeia a porta do container para o localhost
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
