name: Automated Tests

on: pull_request

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    services:
      dynamodb-local:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000
        options: >-
          --health-cmd "curl -f http://localhost:8000/ || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: ‚¨áÔ∏è Checkout Repository para baixar o c√≥digo do projeto
        uses: actions/checkout@v4

      - name: ‚öô Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì¶ Install Dependencies com CI (Clean Install), instala exatamente o package-lock.json
        run: npm ci

      - name: üöÄ Create DynamoDB Local Table
        # Precisamos setar credenciais dummy e a regi√£o para o AWS CLI
        # e apontar o endpoint para o container do 'services'
        env:
          AWS_ACCESS_KEY_ID: FAKE
          AWS_SECRET_ACCESS_KEY: FAKE
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws dynamodb create-table \
            --table-name ton-marketplace-api-dev \
            --attribute-definitions AttributeName=PK,AttributeType=S AttributeName=SK,AttributeType=S \
            --key-schema AttributeName=PK,KeyType=HASH AttributeName=SK,KeyType=RANGE \
            --billing-mode PAY_PER_REQUEST \
            --endpoint-url http://localhost:8000

      - name: üß™ Run Tests
        run: npm test
        env:
          AWS_ACCESS_KEY_ID: FAKE
          AWS_SECRET_ACCESS_KEY: FAKE
          AWS_DEFAULT_REGION: us-east-1
