name: Automated Tests

on: pull_request

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: FAKE
      AWS_SECRET_ACCESS_KEY: FAKE
      AWS_DEFAULT_REGION: us-east-1
    services:
      dynamodb-local:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000
        # Adiciona um health check para esperar o container ficar pronto
        options: >-
          --health-cmd "curl http://localhost:8000/shell"
          --health-interval 5s
          --health-timeout 2s
          --health-retries 5
    steps:
      - name: ‚¨áÔ∏è Checkout Repository para baixar o c√≥digo do projeto
        uses: actions/checkout@v4

      - name: ‚öô Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì¶ Install Dependencies com CI (Clean Install), instala exatamente o package-lock.json
        run: npm ci

      - name: ‚öô Configure AWS CLI (Dummy Credentials)
        # O AWS CLI precisa de credenciais, mesmo para o localhost
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_DEFAULT_REGION
      - name: üöÄ Create DynamoDB Local Table
        # Precisamos setar credenciais dummy e a regi√£o para o AWS CLI
        # e apontar o endpoint para o container do 'services'
        run: |
          echo "Criando tabela no endpoint http://localhost:8000..."
          aws dynamodb create-table \
            --table-name ton-marketplace-api-dev \
            --attribute-definitions AttributeName=PK,AttributeType=S AttributeName=SK,AttributeType=S \
            --key-schema AttributeName=PK,KeyType=HASH AttributeName=SK,KeyType=RANGE \
            --billing-mode PAY_PER_REQUEST \
            --endpoint-url http://localhost:8000

      - name: üß™ Run Tests (Unit + Integration)
        run: npm test
