name: Automated Tests

on: pull_request

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: FAKE
      AWS_SECRET_ACCESS_KEY: FAKE
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - name: ‚¨áÔ∏è Checkout Repository para baixar o c√≥digo do projeto
        uses: actions/checkout@v4

      - name: ‚öô Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: üì¶ Install Dependencies com CI (Clean Install), instala exatamente o package-lock.json
        run: npm ci
      - name: üì¶ Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: ‚öô Configure AWS CLI (Dummy Credentials)
        # O AWS CLI precisa de credenciais, mesmo para o localhost
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_DEFAULT_REGION
      - name: üß™ Run Tests (Unit + Integration)
        # Este script agora orquestra TUDO:
        # 1. Sobe o Docker
        # 2. Espera o DynamoDB ficar pronto
        # 3. Cria a tabela
        # 4. Roda os testes
        # 5. Derruba o Docker
        run: npm test:ci
